### ISSUE TITLE
Inconsistent with cut... and itself

### ISSUE THREAD

**Issue by passcod** [sstadick/hck#12] opened 2021-07-07 10:24 UTC
Consider the following file (named `ppio` below):

```
 589311 be/4 root         16.00 K     16.00 K  0.00 %  0.40 % [kworker/u16:6-events_power_efficient]
 585145 be/4 root          0.00 K     16.00 K  0.00 %  0.06 % [kworker/u16:4-btrfs-endio-meta]
 570665 be/4 root          0.00 K     52.00 K  0.00 %  0.00 % [kworker/u16:58-btrfs-delalloc]
 574135 be/4 passcod       0.00 K     68.00 K  0.00 %  0.00 % firefox-bin [mozStorage #1]
 599167 be/4 root          0.00 K      4.00 K  0.00 %  0.00 % python /usr/bin/iotop -boak -n2 -d5
```

All spaces are actual spaces (0x20) and there's a leading space on each line.

This is an actual payload I wrangled earlier today, and at first I thought hck would have been perfect to deal with it.

I have this fairly reduced case:

```
#> hck -Rd '\s+' -f2- ppio | cut -f1,2,3,4,6,8,10-
589311  be/4    root    16.00   16.00   0.00    0.40    %       [kworker/u16:6-events_power_efficient]
585145  be/4    root    0.00    16.00   0.00    0.06    %       [kworker/u16:4-btrfs-endio-meta]
570665  be/4    root    0.00    52.00   0.00    0.00    %       [kworker/u16:58-btrfs-delalloc] 
574135  be/4    passcod 0.00    68.00   0.00    0.00    %       firefox-bin     [mozStorage     #1]
599167  be/4    root    0.00    4.00    0.00    0.00    %       python  /usr/bin/iotop  -boak   -n2     -d5
```

but:

```
#> hck -Rd '\s+' -f2- ppio | hck -f1,2,3,4,6,8,10-
589311  be/4    root    16.00   16.00   0.00    0.40    %
585145  be/4    root    0.00    16.00   0.00    0.06    %
570665  be/4    root    0.00    52.00   0.00    0.00    %
574135  be/4    passcod 0.00    68.00   0.00    0.00    %       firefox-bin     [mozStorage
599167  be/4    root    0.00    4.00    0.00    0.00    %       python  /usr/bin/iotop  -boak   -n2
```

Whaaat?

---

The reason I introduced the pipe is I couldn't get it working with just a single invocation.

```
#> hck -Rd '\s+' -f2,3,4,5,7,9,11- ppio
589311  be/4    root    16.00   16.00
585145  be/4    root    0.00    16.00
570665  be/4    root    0.00    52.00
574135  be/4    passcod 0.00    68.00
599167  be/4    root    0.00    4.00
```

Using a custom output delimiter and full pattern, I can see it _is_ splitting things up...

```
#> hck -Rd '\s+' -D\| -f1- ppio
|589311|be/4|root|16.00|K|16.00|K|0.00|%|0.40|%|[kworker/u16:6-events_power_efficient]
|585145|be/4|root|0.00|K|16.00|K|0.00|%|0.06|%|[kworker/u16:4-btrfs-endio-meta]
|570665|be/4|root|0.00|K|52.00|K|0.00|%|0.00|%|[kworker/u16:58-btrfs-delalloc]
|574135|be/4|passcod|0.00|K|68.00|K|0.00|%|0.00|%|firefox-bin|[mozStorage|#1]
|599167|be/4|root|0.00|K|4.00|K|0.00|%|0.00|%|python|/usr/bin/iotop|-boak|-n2|-d5
```

...but attempting to select fields based on that again returns weird things. E.g, 2,3 should be the first int and the the priority (`be/4`), right?

```
#> hck -Rd '\s+' -D\| -f2,3 ppio
589311|be/4
585145|be/4
570665|be/4
574135|be/4
599167|be/4
```

Right. And 2,3,4 should add the user to that, right?

```
#> hck -Rd '\s+' -D\| -f2,3,4 ppio
589311|be/4
585145|be/4
570665|be/4
574135|be/4
599167|be/4
```

Err. Okay, maybe there's a hidden field somehow, let's try 2,3,5; 2,3,6; 2,3,7... 2,3,11:

```
#> hck -Rd '\s+' -D\| -f2,3,9 ppio
589311|be/4
585145|be/4
570665|be/4
574135|be/4
599167|be/4
```

Denied.

What if I add a field? 2,3,4,5 _should_ give me int, priority, user, and the first float. But given the above misbehaviour, maybe I'll get... nothing? What would make sense??

```
#> hck -Rd '\s+' -D\| -f2,3,4,5 ppio
589311|be/4
585145|be/4
570665|be/4
574135|be/4
599167|be/4
```

Nothing.

Okay, but what about 2,3,4,6. That should _also_ be nothing, right?

```
#> hck -Rd '\s+' -D\| -f2,3,4,6 ppio
589311|be/4|root
585145|be/4|root
570665|be/4|root
574135|be/4|passcod
599167|be/4|root
```

What the hecking heck?!

**Comment by sstadick** [comment] 2021-07-07 16:27
Thanks for the detailed report! This should be fixed in v0.3.0. Note that I've changed the default delimiter to now be the regex `\s+`, so you no longer need to specify the `-Rd'\s+'` each time.

I've added a few more test cases around this as well 👍 

Please reopen if the issues hasn't been addressed or you find new issues. I've tested with the latest release on your file and seems to be working as intended now:

```
❯ hck  -D\| -f2,3,4 ./test.txt
589311|be/4|root
585145|be/4|root
570665|be/4|root
574135|be/4|passcod
599167|be/4|root
```

**Closed by sstadick** 2021-07-07 16:27 UTC
